//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.UfWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UfWcfService.IUfWcfService")]
    public interface IUfWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUfWcfService/ObterListaUf", ReplyAction="http://tempuri.org/IUfWcfService/ObterListaUfResponse")]
        Domain.Models.Uf[] ObterListaUf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUfWcfService/ObterListaUf", ReplyAction="http://tempuri.org/IUfWcfService/ObterListaUfResponse")]
        System.Threading.Tasks.Task<Domain.Models.Uf[]> ObterListaUfAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUfWcfServiceChannel : WebForm.UfWcfService.IUfWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UfWcfServiceClient : System.ServiceModel.ClientBase<WebForm.UfWcfService.IUfWcfService>, WebForm.UfWcfService.IUfWcfService {
        
        public UfWcfServiceClient() {
        }
        
        public UfWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UfWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UfWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UfWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Domain.Models.Uf[] ObterListaUf() {
            return base.Channel.ObterListaUf();
        }
        
        public System.Threading.Tasks.Task<Domain.Models.Uf[]> ObterListaUfAsync() {
            return base.Channel.ObterListaUfAsync();
        }
    }
}
